# Generated by Django 3.0.2 on 2020-01-12 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='login_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=20)),
                ('psw', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='student_info',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=50)),
                ('student_phone', models.IntegerField()),
                ('student_email', models.CharField(max_length=50)),
                ('student_password', models.CharField(max_length=60)),
                ('student_city', models.CharField(max_length=20)),
                ('student_street', models.CharField(max_length=20)),
            ],
        ),
    ]
